CREATE DATABASE ${DB_NAME}
GO

USE ${DB_NAME}
GO

CREATE LOGIN ${DB_USER} WITH PASSWORD = '${DB_PASS}', CHECK_POLICY = OFF;
CREATE USER ${DB_USER} FOR LOGIN ${DB_USER};
GRANT ALTER TO ${DB_USER};
GRANT CONTROL TO ${DB_USER};
GO